version: "openvpn-build-{build}"

image:
- Visual Studio 2017

skip_commits:
  files:
    - .travis.yml

environment:
  CBUILD: x86_64-pc-linux-gnu
  matrix:
    - BUILDSYSTEM: VS2017

for:
  -
    matrix:
      only:
        - BUILDSYSTEM: cygwin
    build_script:
      - "%CYGWIN%\\setup-%ARCH%.exe -g -q -P mingw64-i686-openssl,mingw64-x86_64-openssl,cygwin-devel,unzip,dos2unix,patch"
      - "%CYGWIN%\\bin\\bash -lc 'cp `which true` /usr/bin/man2html'"
      - "%CYGWIN%\\bin\\bash -lc 'cd /cygdrive/c/projects/%APPVEYOR_PROJECT_SLUG% ; generic/build'"
    artifacts:
      - path: generic/image/openvpn/bin

  -
    matrix:
      only:
        - BUILDSYSTEM: VS2017
    init:
      - choco install -y --allow-empty-checksums nasm
    build_script:
      - msvc/build.bat
    artifacts:
      - path: msvc/image/bin
