# The name of our workflow
name: Build
on:
  push:
  pull_request:

jobs:
  msvc:
    strategy:
      matrix:
        arch: [x86, amd64, arm64]

    env:
      CMAKE: cmake.exe
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      OSSL: ossl3
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\openvpn-build\windows-msi\vcpkg-ports
      WIX: ${{ github.workspace }}\wix\

    name: 'openvpn-build'
    runs-on: windows-2019

    steps:
      - name: Push
        if: ${{ github.event_name == 'push' }}
        run: |
          Write-Host "Push"

      - name: Pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          Write-Host "Pull request"
      
